version: '3'


services:

  leonid_the_chat_bot:
      image: leonid_the_chat_bot:latest
      build: ./Leonid
      ports:
        - 5001:5001
      environment:
        - MODEL_PATH=./models/ggml-vicuna-13b-4bit-rev1.bin
        - MAX_CONTEXT_LENGHT=2400







